import Head from 'next/head'
import EventList from '../components/event/EventList'
import { Event, getFeaturedEvents } from '../components/helpers/db-utils'
import Subscription from '../components/ui/Subscription'

type Props = {
  featuredEvents: Event[]
}

export default function Home({ featuredEvents }: Props) {
  return (
    <>
      <Head>
        <title>Events</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Subscription />
      <EventList items={featuredEvents} />
    </>
  )
}

export const getStaticProps = async () => {
  const featuredEvents = await getFeaturedEvents()
  return {
    props: {
      featuredEvents,
    },
    revalidate: 1800,
  }
}
